version: '3.3'
services:
  registry:
    image: registry:2
    networks: [traefik-public]
    volumes:
      - ${registry_local_volume}:/var/lib/registry
      - ${host_src_path}/auth/htpasswd:/auth/.htpasswd:ro
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/.htpasswd
      REGISTRY_STORAGE_DELETE_ENABLED: "yes"
      REGISTRY_STORAGE_CACHE_BLOBDESCRIPTOR: redis
      REGISTRY_REDIS_ADDR: redis:6379
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.registry.rule=Host(`${docker_subdomain}.${server_domain}`)
        - traefik.http.routers.registry.entrypoints=https
        - traefik.http.routers.registry.tls=true
        - traefik.http.routers.registry.tls.certresolver=le
        - traefik.http.services.registry.loadbalancer.server.port=5000
        - traefik.http.services.registry.loadbalancer.passhostheader=true
        - traefik.http.routers.registry.middlewares=compress@file,large-upload@file,registry-ratelimit@file

networks:
  traefik-public:
    external: true