version: '3'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - traefik-public
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    command: redis-server --maxmemory 8gb --maxmemory-policy allkeys-lru

networks:
  traefik-public:
    external: true 